// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: pkg/rmcp/rmcp.proto

package rmcp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RemoteControl struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MouseX          int32                  `protobuf:"varint,1,opt,name=mouse_x,json=mouseX,proto3" json:"mouse_x,omitempty"`
	MouseY          int32                  `protobuf:"varint,2,opt,name=mouse_y,json=mouseY,proto3" json:"mouse_y,omitempty"`
	MouseZ          int32                  `protobuf:"varint,3,opt,name=mouse_z,json=mouseZ,proto3" json:"mouse_z,omitempty"`
	LeftButtonDown  bool                   `protobuf:"varint,4,opt,name=left_button_down,json=leftButtonDown,proto3" json:"left_button_down,omitempty"`
	RightButtonDown bool                   `protobuf:"varint,5,opt,name=right_button_down,json=rightButtonDown,proto3" json:"right_button_down,omitempty"`
	KeyboardValue   uint32                 `protobuf:"varint,6,opt,name=keyboard_value,json=keyboardValue,proto3" json:"keyboard_value,omitempty"`
	MidButtonDown   bool                   `protobuf:"varint,7,opt,name=mid_button_down,json=midButtonDown,proto3" json:"mid_button_down,omitempty"`
	Data            []byte                 `protobuf:"bytes,8,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RemoteControl) Reset() {
	*x = RemoteControl{}
	mi := &file_pkg_rmcp_rmcp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteControl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteControl) ProtoMessage() {}

func (x *RemoteControl) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rmcp_rmcp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteControl.ProtoReflect.Descriptor instead.
func (*RemoteControl) Descriptor() ([]byte, []int) {
	return file_pkg_rmcp_rmcp_proto_rawDescGZIP(), []int{0}
}

func (x *RemoteControl) GetMouseX() int32 {
	if x != nil {
		return x.MouseX
	}
	return 0
}

func (x *RemoteControl) GetMouseY() int32 {
	if x != nil {
		return x.MouseY
	}
	return 0
}

func (x *RemoteControl) GetMouseZ() int32 {
	if x != nil {
		return x.MouseZ
	}
	return 0
}

func (x *RemoteControl) GetLeftButtonDown() bool {
	if x != nil {
		return x.LeftButtonDown
	}
	return false
}

func (x *RemoteControl) GetRightButtonDown() bool {
	if x != nil {
		return x.RightButtonDown
	}
	return false
}

func (x *RemoteControl) GetKeyboardValue() uint32 {
	if x != nil {
		return x.KeyboardValue
	}
	return 0
}

func (x *RemoteControl) GetMidButtonDown() bool {
	if x != nil {
		return x.MidButtonDown
	}
	return false
}

func (x *RemoteControl) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type GameStatus struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CurrentRound      uint32                 `protobuf:"varint,1,opt,name=current_round,json=currentRound,proto3" json:"current_round,omitempty"`
	TotalRounds       uint32                 `protobuf:"varint,2,opt,name=total_rounds,json=totalRounds,proto3" json:"total_rounds,omitempty"`
	RedScore          uint32                 `protobuf:"varint,3,opt,name=red_score,json=redScore,proto3" json:"red_score,omitempty"`
	BlueScore         uint32                 `protobuf:"varint,4,opt,name=blue_score,json=blueScore,proto3" json:"blue_score,omitempty"`
	CurrentStage      uint32                 `protobuf:"varint,5,opt,name=current_stage,json=currentStage,proto3" json:"current_stage,omitempty"`
	StageCountdownSec int32                  `protobuf:"varint,6,opt,name=stage_countdown_sec,json=stageCountdownSec,proto3" json:"stage_countdown_sec,omitempty"`
	StageElapsedSec   int32                  `protobuf:"varint,7,opt,name=stage_elapsed_sec,json=stageElapsedSec,proto3" json:"stage_elapsed_sec,omitempty"`
	IsPaused          bool                   `protobuf:"varint,8,opt,name=is_paused,json=isPaused,proto3" json:"is_paused,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GameStatus) Reset() {
	*x = GameStatus{}
	mi := &file_pkg_rmcp_rmcp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameStatus) ProtoMessage() {}

func (x *GameStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rmcp_rmcp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameStatus.ProtoReflect.Descriptor instead.
func (*GameStatus) Descriptor() ([]byte, []int) {
	return file_pkg_rmcp_rmcp_proto_rawDescGZIP(), []int{1}
}

func (x *GameStatus) GetCurrentRound() uint32 {
	if x != nil {
		return x.CurrentRound
	}
	return 0
}

func (x *GameStatus) GetTotalRounds() uint32 {
	if x != nil {
		return x.TotalRounds
	}
	return 0
}

func (x *GameStatus) GetRedScore() uint32 {
	if x != nil {
		return x.RedScore
	}
	return 0
}

func (x *GameStatus) GetBlueScore() uint32 {
	if x != nil {
		return x.BlueScore
	}
	return 0
}

func (x *GameStatus) GetCurrentStage() uint32 {
	if x != nil {
		return x.CurrentStage
	}
	return 0
}

func (x *GameStatus) GetStageCountdownSec() int32 {
	if x != nil {
		return x.StageCountdownSec
	}
	return 0
}

func (x *GameStatus) GetStageElapsedSec() int32 {
	if x != nil {
		return x.StageElapsedSec
	}
	return 0
}

func (x *GameStatus) GetIsPaused() bool {
	if x != nil {
		return x.IsPaused
	}
	return false
}

type GlobalUnitStatus struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BaseHealth      uint32                 `protobuf:"varint,1,opt,name=base_health,json=baseHealth,proto3" json:"base_health,omitempty"`
	BaseStatus      uint32                 `protobuf:"varint,2,opt,name=base_status,json=baseStatus,proto3" json:"base_status,omitempty"`
	BaseShield      uint32                 `protobuf:"varint,3,opt,name=base_shield,json=baseShield,proto3" json:"base_shield,omitempty"`
	OutpostHealth   uint32                 `protobuf:"varint,4,opt,name=outpost_health,json=outpostHealth,proto3" json:"outpost_health,omitempty"`
	OutpostStatus   uint32                 `protobuf:"varint,5,opt,name=outpost_status,json=outpostStatus,proto3" json:"outpost_status,omitempty"`
	RobotHealth     []uint32               `protobuf:"varint,6,rep,packed,name=robot_health,json=robotHealth,proto3" json:"robot_health,omitempty"`
	RobotBullets    []int32                `protobuf:"varint,7,rep,packed,name=robot_bullets,json=robotBullets,proto3" json:"robot_bullets,omitempty"`
	TotalDamageRed  uint32                 `protobuf:"varint,8,opt,name=total_damage_red,json=totalDamageRed,proto3" json:"total_damage_red,omitempty"`
	TotalDamageBlue uint32                 `protobuf:"varint,9,opt,name=total_damage_blue,json=totalDamageBlue,proto3" json:"total_damage_blue,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GlobalUnitStatus) Reset() {
	*x = GlobalUnitStatus{}
	mi := &file_pkg_rmcp_rmcp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalUnitStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalUnitStatus) ProtoMessage() {}

func (x *GlobalUnitStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rmcp_rmcp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalUnitStatus.ProtoReflect.Descriptor instead.
func (*GlobalUnitStatus) Descriptor() ([]byte, []int) {
	return file_pkg_rmcp_rmcp_proto_rawDescGZIP(), []int{2}
}

func (x *GlobalUnitStatus) GetBaseHealth() uint32 {
	if x != nil {
		return x.BaseHealth
	}
	return 0
}

func (x *GlobalUnitStatus) GetBaseStatus() uint32 {
	if x != nil {
		return x.BaseStatus
	}
	return 0
}

func (x *GlobalUnitStatus) GetBaseShield() uint32 {
	if x != nil {
		return x.BaseShield
	}
	return 0
}

func (x *GlobalUnitStatus) GetOutpostHealth() uint32 {
	if x != nil {
		return x.OutpostHealth
	}
	return 0
}

func (x *GlobalUnitStatus) GetOutpostStatus() uint32 {
	if x != nil {
		return x.OutpostStatus
	}
	return 0
}

func (x *GlobalUnitStatus) GetRobotHealth() []uint32 {
	if x != nil {
		return x.RobotHealth
	}
	return nil
}

func (x *GlobalUnitStatus) GetRobotBullets() []int32 {
	if x != nil {
		return x.RobotBullets
	}
	return nil
}

func (x *GlobalUnitStatus) GetTotalDamageRed() uint32 {
	if x != nil {
		return x.TotalDamageRed
	}
	return 0
}

func (x *GlobalUnitStatus) GetTotalDamageBlue() uint32 {
	if x != nil {
		return x.TotalDamageBlue
	}
	return 0
}

type GlobalLogisticsStatus struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	RemainingEconomy     uint32                 `protobuf:"varint,1,opt,name=remaining_economy,json=remainingEconomy,proto3" json:"remaining_economy,omitempty"`
	TotalEconomyObtained uint64                 `protobuf:"varint,2,opt,name=total_economy_obtained,json=totalEconomyObtained,proto3" json:"total_economy_obtained,omitempty"`
	TechLevel            uint32                 `protobuf:"varint,3,opt,name=tech_level,json=techLevel,proto3" json:"tech_level,omitempty"`
	EncryptionLevel      uint32                 `protobuf:"varint,4,opt,name=encryption_level,json=encryptionLevel,proto3" json:"encryption_level,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GlobalLogisticsStatus) Reset() {
	*x = GlobalLogisticsStatus{}
	mi := &file_pkg_rmcp_rmcp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalLogisticsStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalLogisticsStatus) ProtoMessage() {}

func (x *GlobalLogisticsStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rmcp_rmcp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalLogisticsStatus.ProtoReflect.Descriptor instead.
func (*GlobalLogisticsStatus) Descriptor() ([]byte, []int) {
	return file_pkg_rmcp_rmcp_proto_rawDescGZIP(), []int{3}
}

func (x *GlobalLogisticsStatus) GetRemainingEconomy() uint32 {
	if x != nil {
		return x.RemainingEconomy
	}
	return 0
}

func (x *GlobalLogisticsStatus) GetTotalEconomyObtained() uint64 {
	if x != nil {
		return x.TotalEconomyObtained
	}
	return 0
}

func (x *GlobalLogisticsStatus) GetTechLevel() uint32 {
	if x != nil {
		return x.TechLevel
	}
	return 0
}

func (x *GlobalLogisticsStatus) GetEncryptionLevel() uint32 {
	if x != nil {
		return x.EncryptionLevel
	}
	return 0
}

type GlobalSpecialMechanism struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MechanismId      []uint32               `protobuf:"varint,1,rep,packed,name=mechanism_id,json=mechanismId,proto3" json:"mechanism_id,omitempty"`
	MechanismTimeSec []int32                `protobuf:"varint,2,rep,packed,name=mechanism_time_sec,json=mechanismTimeSec,proto3" json:"mechanism_time_sec,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GlobalSpecialMechanism) Reset() {
	*x = GlobalSpecialMechanism{}
	mi := &file_pkg_rmcp_rmcp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalSpecialMechanism) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalSpecialMechanism) ProtoMessage() {}

func (x *GlobalSpecialMechanism) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rmcp_rmcp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalSpecialMechanism.ProtoReflect.Descriptor instead.
func (*GlobalSpecialMechanism) Descriptor() ([]byte, []int) {
	return file_pkg_rmcp_rmcp_proto_rawDescGZIP(), []int{4}
}

func (x *GlobalSpecialMechanism) GetMechanismId() []uint32 {
	if x != nil {
		return x.MechanismId
	}
	return nil
}

func (x *GlobalSpecialMechanism) GetMechanismTimeSec() []int32 {
	if x != nil {
		return x.MechanismTimeSec
	}
	return nil
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       int32                  `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Param         string                 `protobuf:"bytes,2,opt,name=param,proto3" json:"param,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_pkg_rmcp_rmcp_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rmcp_rmcp_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_pkg_rmcp_rmcp_proto_rawDescGZIP(), []int{5}
}

func (x *Event) GetEventId() int32 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *Event) GetParam() string {
	if x != nil {
		return x.Param
	}
	return ""
}

type RobotInjuryStat struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	TotalDamage           uint32                 `protobuf:"varint,1,opt,name=total_damage,json=totalDamage,proto3" json:"total_damage,omitempty"`
	CollisionDamage       uint32                 `protobuf:"varint,2,opt,name=collision_damage,json=collisionDamage,proto3" json:"collision_damage,omitempty"`
	SmallProjectileDamage uint32                 `protobuf:"varint,3,opt,name=small_projectile_damage,json=smallProjectileDamage,proto3" json:"small_projectile_damage,omitempty"`
	LargeProjectileDamage uint32                 `protobuf:"varint,4,opt,name=large_projectile_damage,json=largeProjectileDamage,proto3" json:"large_projectile_damage,omitempty"`
	DartSplashDamage      uint32                 `protobuf:"varint,5,opt,name=dart_splash_damage,json=dartSplashDamage,proto3" json:"dart_splash_damage,omitempty"`
	ModuleOfflineDamage   uint32                 `protobuf:"varint,6,opt,name=module_offline_damage,json=moduleOfflineDamage,proto3" json:"module_offline_damage,omitempty"`
	WifiOfflineDamage     uint32                 `protobuf:"varint,7,opt,name=wifi_offline_damage,json=wifiOfflineDamage,proto3" json:"wifi_offline_damage,omitempty"`
	PenaltyDamage         uint32                 `protobuf:"varint,8,opt,name=penalty_damage,json=penaltyDamage,proto3" json:"penalty_damage,omitempty"`
	ServerKillDamage      uint32                 `protobuf:"varint,9,opt,name=server_kill_damage,json=serverKillDamage,proto3" json:"server_kill_damage,omitempty"`
	KillerId              uint32                 `protobuf:"varint,10,opt,name=killer_id,json=killerId,proto3" json:"killer_id,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *RobotInjuryStat) Reset() {
	*x = RobotInjuryStat{}
	mi := &file_pkg_rmcp_rmcp_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RobotInjuryStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RobotInjuryStat) ProtoMessage() {}

func (x *RobotInjuryStat) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rmcp_rmcp_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RobotInjuryStat.ProtoReflect.Descriptor instead.
func (*RobotInjuryStat) Descriptor() ([]byte, []int) {
	return file_pkg_rmcp_rmcp_proto_rawDescGZIP(), []int{6}
}

func (x *RobotInjuryStat) GetTotalDamage() uint32 {
	if x != nil {
		return x.TotalDamage
	}
	return 0
}

func (x *RobotInjuryStat) GetCollisionDamage() uint32 {
	if x != nil {
		return x.CollisionDamage
	}
	return 0
}

func (x *RobotInjuryStat) GetSmallProjectileDamage() uint32 {
	if x != nil {
		return x.SmallProjectileDamage
	}
	return 0
}

func (x *RobotInjuryStat) GetLargeProjectileDamage() uint32 {
	if x != nil {
		return x.LargeProjectileDamage
	}
	return 0
}

func (x *RobotInjuryStat) GetDartSplashDamage() uint32 {
	if x != nil {
		return x.DartSplashDamage
	}
	return 0
}

func (x *RobotInjuryStat) GetModuleOfflineDamage() uint32 {
	if x != nil {
		return x.ModuleOfflineDamage
	}
	return 0
}

func (x *RobotInjuryStat) GetWifiOfflineDamage() uint32 {
	if x != nil {
		return x.WifiOfflineDamage
	}
	return 0
}

func (x *RobotInjuryStat) GetPenaltyDamage() uint32 {
	if x != nil {
		return x.PenaltyDamage
	}
	return 0
}

func (x *RobotInjuryStat) GetServerKillDamage() uint32 {
	if x != nil {
		return x.ServerKillDamage
	}
	return 0
}

func (x *RobotInjuryStat) GetKillerId() uint32 {
	if x != nil {
		return x.KillerId
	}
	return 0
}

type RobotRespawnStatus struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	IsPendingRespawn       bool                   `protobuf:"varint,1,opt,name=is_pending_respawn,json=isPendingRespawn,proto3" json:"is_pending_respawn,omitempty"`
	TotalRespawnProgress   uint32                 `protobuf:"varint,2,opt,name=total_respawn_progress,json=totalRespawnProgress,proto3" json:"total_respawn_progress,omitempty"`
	CurrentRespawnProgress uint32                 `protobuf:"varint,3,opt,name=current_respawn_progress,json=currentRespawnProgress,proto3" json:"current_respawn_progress,omitempty"`
	CanFreeRespawn         bool                   `protobuf:"varint,4,opt,name=can_free_respawn,json=canFreeRespawn,proto3" json:"can_free_respawn,omitempty"`
	GoldCostForRespawn     uint32                 `protobuf:"varint,5,opt,name=gold_cost_for_respawn,json=goldCostForRespawn,proto3" json:"gold_cost_for_respawn,omitempty"`
	CanPayForRespawn       bool                   `protobuf:"varint,6,opt,name=can_pay_for_respawn,json=canPayForRespawn,proto3" json:"can_pay_for_respawn,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RobotRespawnStatus) Reset() {
	*x = RobotRespawnStatus{}
	mi := &file_pkg_rmcp_rmcp_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RobotRespawnStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RobotRespawnStatus) ProtoMessage() {}

func (x *RobotRespawnStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rmcp_rmcp_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RobotRespawnStatus.ProtoReflect.Descriptor instead.
func (*RobotRespawnStatus) Descriptor() ([]byte, []int) {
	return file_pkg_rmcp_rmcp_proto_rawDescGZIP(), []int{7}
}

func (x *RobotRespawnStatus) GetIsPendingRespawn() bool {
	if x != nil {
		return x.IsPendingRespawn
	}
	return false
}

func (x *RobotRespawnStatus) GetTotalRespawnProgress() uint32 {
	if x != nil {
		return x.TotalRespawnProgress
	}
	return 0
}

func (x *RobotRespawnStatus) GetCurrentRespawnProgress() uint32 {
	if x != nil {
		return x.CurrentRespawnProgress
	}
	return 0
}

func (x *RobotRespawnStatus) GetCanFreeRespawn() bool {
	if x != nil {
		return x.CanFreeRespawn
	}
	return false
}

func (x *RobotRespawnStatus) GetGoldCostForRespawn() uint32 {
	if x != nil {
		return x.GoldCostForRespawn
	}
	return 0
}

func (x *RobotRespawnStatus) GetCanPayForRespawn() bool {
	if x != nil {
		return x.CanPayForRespawn
	}
	return false
}

type RobotStaticStatus struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	ConnectionState          uint32                 `protobuf:"varint,1,opt,name=connection_state,json=connectionState,proto3" json:"connection_state,omitempty"`
	FieldState               uint32                 `protobuf:"varint,2,opt,name=field_state,json=fieldState,proto3" json:"field_state,omitempty"`
	AliveState               uint32                 `protobuf:"varint,3,opt,name=alive_state,json=aliveState,proto3" json:"alive_state,omitempty"`
	RobotId                  uint32                 `protobuf:"varint,4,opt,name=robot_id,json=robotId,proto3" json:"robot_id,omitempty"`
	RobotType                uint32                 `protobuf:"varint,5,opt,name=robot_type,json=robotType,proto3" json:"robot_type,omitempty"`
	PerformanceSystemShooter uint32                 `protobuf:"varint,6,opt,name=performance_system_shooter,json=performanceSystemShooter,proto3" json:"performance_system_shooter,omitempty"`
	PerformanceSystemChassis uint32                 `protobuf:"varint,7,opt,name=performance_system_chassis,json=performanceSystemChassis,proto3" json:"performance_system_chassis,omitempty"`
	Level                    uint32                 `protobuf:"varint,8,opt,name=level,proto3" json:"level,omitempty"`
	MaxHealth                uint32                 `protobuf:"varint,9,opt,name=max_health,json=maxHealth,proto3" json:"max_health,omitempty"`
	MaxHeat                  uint32                 `protobuf:"varint,10,opt,name=max_heat,json=maxHeat,proto3" json:"max_heat,omitempty"`
	HeatCooldownRate         float32                `protobuf:"fixed32,11,opt,name=heat_cooldown_rate,json=heatCooldownRate,proto3" json:"heat_cooldown_rate,omitempty"`
	MaxPower                 uint32                 `protobuf:"varint,12,opt,name=max_power,json=maxPower,proto3" json:"max_power,omitempty"`
	MaxBufferEnergy          uint32                 `protobuf:"varint,13,opt,name=max_buffer_energy,json=maxBufferEnergy,proto3" json:"max_buffer_energy,omitempty"`
	MaxChassisEnergy         uint32                 `protobuf:"varint,14,opt,name=max_chassis_energy,json=maxChassisEnergy,proto3" json:"max_chassis_energy,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *RobotStaticStatus) Reset() {
	*x = RobotStaticStatus{}
	mi := &file_pkg_rmcp_rmcp_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RobotStaticStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RobotStaticStatus) ProtoMessage() {}

func (x *RobotStaticStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rmcp_rmcp_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RobotStaticStatus.ProtoReflect.Descriptor instead.
func (*RobotStaticStatus) Descriptor() ([]byte, []int) {
	return file_pkg_rmcp_rmcp_proto_rawDescGZIP(), []int{8}
}

func (x *RobotStaticStatus) GetConnectionState() uint32 {
	if x != nil {
		return x.ConnectionState
	}
	return 0
}

func (x *RobotStaticStatus) GetFieldState() uint32 {
	if x != nil {
		return x.FieldState
	}
	return 0
}

func (x *RobotStaticStatus) GetAliveState() uint32 {
	if x != nil {
		return x.AliveState
	}
	return 0
}

func (x *RobotStaticStatus) GetRobotId() uint32 {
	if x != nil {
		return x.RobotId
	}
	return 0
}

func (x *RobotStaticStatus) GetRobotType() uint32 {
	if x != nil {
		return x.RobotType
	}
	return 0
}

func (x *RobotStaticStatus) GetPerformanceSystemShooter() uint32 {
	if x != nil {
		return x.PerformanceSystemShooter
	}
	return 0
}

func (x *RobotStaticStatus) GetPerformanceSystemChassis() uint32 {
	if x != nil {
		return x.PerformanceSystemChassis
	}
	return 0
}

func (x *RobotStaticStatus) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *RobotStaticStatus) GetMaxHealth() uint32 {
	if x != nil {
		return x.MaxHealth
	}
	return 0
}

func (x *RobotStaticStatus) GetMaxHeat() uint32 {
	if x != nil {
		return x.MaxHeat
	}
	return 0
}

func (x *RobotStaticStatus) GetHeatCooldownRate() float32 {
	if x != nil {
		return x.HeatCooldownRate
	}
	return 0
}

func (x *RobotStaticStatus) GetMaxPower() uint32 {
	if x != nil {
		return x.MaxPower
	}
	return 0
}

func (x *RobotStaticStatus) GetMaxBufferEnergy() uint32 {
	if x != nil {
		return x.MaxBufferEnergy
	}
	return 0
}

func (x *RobotStaticStatus) GetMaxChassisEnergy() uint32 {
	if x != nil {
		return x.MaxChassisEnergy
	}
	return 0
}

type RobotDynamicStatus struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	CurrentHealth          uint32                 `protobuf:"varint,1,opt,name=current_health,json=currentHealth,proto3" json:"current_health,omitempty"`
	CurrentHeat            float32                `protobuf:"fixed32,2,opt,name=current_heat,json=currentHeat,proto3" json:"current_heat,omitempty"`
	LastProjectileFireRate float32                `protobuf:"fixed32,3,opt,name=last_projectile_fire_rate,json=lastProjectileFireRate,proto3" json:"last_projectile_fire_rate,omitempty"`
	CurrentChassisEnergy   uint32                 `protobuf:"varint,4,opt,name=current_chassis_energy,json=currentChassisEnergy,proto3" json:"current_chassis_energy,omitempty"`
	CurrentBufferEnergy    uint32                 `protobuf:"varint,5,opt,name=current_buffer_energy,json=currentBufferEnergy,proto3" json:"current_buffer_energy,omitempty"`
	CurrentExperience      uint32                 `protobuf:"varint,6,opt,name=current_experience,json=currentExperience,proto3" json:"current_experience,omitempty"`
	ExperienceForUpgrade   uint32                 `protobuf:"varint,7,opt,name=experience_for_upgrade,json=experienceForUpgrade,proto3" json:"experience_for_upgrade,omitempty"`
	TotalProjectilesFired  uint32                 `protobuf:"varint,8,opt,name=total_projectiles_fired,json=totalProjectilesFired,proto3" json:"total_projectiles_fired,omitempty"`
	RemainingAmmo          uint32                 `protobuf:"varint,9,opt,name=remaining_ammo,json=remainingAmmo,proto3" json:"remaining_ammo,omitempty"`
	IsOutOfCombat          bool                   `protobuf:"varint,10,opt,name=is_out_of_combat,json=isOutOfCombat,proto3" json:"is_out_of_combat,omitempty"`
	OutOfCombatCountdown   uint32                 `protobuf:"varint,11,opt,name=out_of_combat_countdown,json=outOfCombatCountdown,proto3" json:"out_of_combat_countdown,omitempty"`
	CanRemoteHeal          bool                   `protobuf:"varint,12,opt,name=can_remote_heal,json=canRemoteHeal,proto3" json:"can_remote_heal,omitempty"`
	CanRemoteAmmo          bool                   `protobuf:"varint,13,opt,name=can_remote_ammo,json=canRemoteAmmo,proto3" json:"can_remote_ammo,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RobotDynamicStatus) Reset() {
	*x = RobotDynamicStatus{}
	mi := &file_pkg_rmcp_rmcp_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RobotDynamicStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RobotDynamicStatus) ProtoMessage() {}

func (x *RobotDynamicStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rmcp_rmcp_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RobotDynamicStatus.ProtoReflect.Descriptor instead.
func (*RobotDynamicStatus) Descriptor() ([]byte, []int) {
	return file_pkg_rmcp_rmcp_proto_rawDescGZIP(), []int{9}
}

func (x *RobotDynamicStatus) GetCurrentHealth() uint32 {
	if x != nil {
		return x.CurrentHealth
	}
	return 0
}

func (x *RobotDynamicStatus) GetCurrentHeat() float32 {
	if x != nil {
		return x.CurrentHeat
	}
	return 0
}

func (x *RobotDynamicStatus) GetLastProjectileFireRate() float32 {
	if x != nil {
		return x.LastProjectileFireRate
	}
	return 0
}

func (x *RobotDynamicStatus) GetCurrentChassisEnergy() uint32 {
	if x != nil {
		return x.CurrentChassisEnergy
	}
	return 0
}

func (x *RobotDynamicStatus) GetCurrentBufferEnergy() uint32 {
	if x != nil {
		return x.CurrentBufferEnergy
	}
	return 0
}

func (x *RobotDynamicStatus) GetCurrentExperience() uint32 {
	if x != nil {
		return x.CurrentExperience
	}
	return 0
}

func (x *RobotDynamicStatus) GetExperienceForUpgrade() uint32 {
	if x != nil {
		return x.ExperienceForUpgrade
	}
	return 0
}

func (x *RobotDynamicStatus) GetTotalProjectilesFired() uint32 {
	if x != nil {
		return x.TotalProjectilesFired
	}
	return 0
}

func (x *RobotDynamicStatus) GetRemainingAmmo() uint32 {
	if x != nil {
		return x.RemainingAmmo
	}
	return 0
}

func (x *RobotDynamicStatus) GetIsOutOfCombat() bool {
	if x != nil {
		return x.IsOutOfCombat
	}
	return false
}

func (x *RobotDynamicStatus) GetOutOfCombatCountdown() uint32 {
	if x != nil {
		return x.OutOfCombatCountdown
	}
	return 0
}

func (x *RobotDynamicStatus) GetCanRemoteHeal() bool {
	if x != nil {
		return x.CanRemoteHeal
	}
	return false
}

func (x *RobotDynamicStatus) GetCanRemoteAmmo() bool {
	if x != nil {
		return x.CanRemoteAmmo
	}
	return false
}

type RobotModuleStatus struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PowerManager      uint32                 `protobuf:"varint,1,opt,name=power_manager,json=powerManager,proto3" json:"power_manager,omitempty"`
	Rfid              uint32                 `protobuf:"varint,2,opt,name=rfid,proto3" json:"rfid,omitempty"`
	LightStrip        uint32                 `protobuf:"varint,3,opt,name=light_strip,json=lightStrip,proto3" json:"light_strip,omitempty"`
	SmallShooter      uint32                 `protobuf:"varint,4,opt,name=small_shooter,json=smallShooter,proto3" json:"small_shooter,omitempty"`
	BigShooter        uint32                 `protobuf:"varint,5,opt,name=big_shooter,json=bigShooter,proto3" json:"big_shooter,omitempty"`
	Uwb               uint32                 `protobuf:"varint,6,opt,name=uwb,proto3" json:"uwb,omitempty"`
	Armor             uint32                 `protobuf:"varint,7,opt,name=armor,proto3" json:"armor,omitempty"`
	VideoTransmission uint32                 `protobuf:"varint,8,opt,name=video_transmission,json=videoTransmission,proto3" json:"video_transmission,omitempty"`
	Capacitor         uint32                 `protobuf:"varint,9,opt,name=capacitor,proto3" json:"capacitor,omitempty"`
	MainController    uint32                 `protobuf:"varint,10,opt,name=main_controller,json=mainController,proto3" json:"main_controller,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RobotModuleStatus) Reset() {
	*x = RobotModuleStatus{}
	mi := &file_pkg_rmcp_rmcp_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RobotModuleStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RobotModuleStatus) ProtoMessage() {}

func (x *RobotModuleStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rmcp_rmcp_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RobotModuleStatus.ProtoReflect.Descriptor instead.
func (*RobotModuleStatus) Descriptor() ([]byte, []int) {
	return file_pkg_rmcp_rmcp_proto_rawDescGZIP(), []int{10}
}

func (x *RobotModuleStatus) GetPowerManager() uint32 {
	if x != nil {
		return x.PowerManager
	}
	return 0
}

func (x *RobotModuleStatus) GetRfid() uint32 {
	if x != nil {
		return x.Rfid
	}
	return 0
}

func (x *RobotModuleStatus) GetLightStrip() uint32 {
	if x != nil {
		return x.LightStrip
	}
	return 0
}

func (x *RobotModuleStatus) GetSmallShooter() uint32 {
	if x != nil {
		return x.SmallShooter
	}
	return 0
}

func (x *RobotModuleStatus) GetBigShooter() uint32 {
	if x != nil {
		return x.BigShooter
	}
	return 0
}

func (x *RobotModuleStatus) GetUwb() uint32 {
	if x != nil {
		return x.Uwb
	}
	return 0
}

func (x *RobotModuleStatus) GetArmor() uint32 {
	if x != nil {
		return x.Armor
	}
	return 0
}

func (x *RobotModuleStatus) GetVideoTransmission() uint32 {
	if x != nil {
		return x.VideoTransmission
	}
	return 0
}

func (x *RobotModuleStatus) GetCapacitor() uint32 {
	if x != nil {
		return x.Capacitor
	}
	return 0
}

func (x *RobotModuleStatus) GetMainController() uint32 {
	if x != nil {
		return x.MainController
	}
	return 0
}

type RobotPosition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z             float32                `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
	Yaw           float32                `protobuf:"fixed32,4,opt,name=yaw,proto3" json:"yaw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RobotPosition) Reset() {
	*x = RobotPosition{}
	mi := &file_pkg_rmcp_rmcp_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RobotPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RobotPosition) ProtoMessage() {}

func (x *RobotPosition) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rmcp_rmcp_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RobotPosition.ProtoReflect.Descriptor instead.
func (*RobotPosition) Descriptor() ([]byte, []int) {
	return file_pkg_rmcp_rmcp_proto_rawDescGZIP(), []int{11}
}

func (x *RobotPosition) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *RobotPosition) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *RobotPosition) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *RobotPosition) GetYaw() float32 {
	if x != nil {
		return x.Yaw
	}
	return 0
}

type Buff struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RobotId       uint32                 `protobuf:"varint,1,opt,name=robot_id,json=robotId,proto3" json:"robot_id,omitempty"`
	BuffType      uint32                 `protobuf:"varint,2,opt,name=buff_type,json=buffType,proto3" json:"buff_type,omitempty"`
	BuffLevel     int32                  `protobuf:"varint,3,opt,name=buff_level,json=buffLevel,proto3" json:"buff_level,omitempty"`
	BuffMaxTime   uint32                 `protobuf:"varint,4,opt,name=buff_max_time,json=buffMaxTime,proto3" json:"buff_max_time,omitempty"`
	BuffLeftTime  uint32                 `protobuf:"varint,5,opt,name=buff_left_time,json=buffLeftTime,proto3" json:"buff_left_time,omitempty"`
	MsgParams     string                 `protobuf:"bytes,6,opt,name=msg_params,json=msgParams,proto3" json:"msg_params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Buff) Reset() {
	*x = Buff{}
	mi := &file_pkg_rmcp_rmcp_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Buff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Buff) ProtoMessage() {}

func (x *Buff) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rmcp_rmcp_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Buff.ProtoReflect.Descriptor instead.
func (*Buff) Descriptor() ([]byte, []int) {
	return file_pkg_rmcp_rmcp_proto_rawDescGZIP(), []int{12}
}

func (x *Buff) GetRobotId() uint32 {
	if x != nil {
		return x.RobotId
	}
	return 0
}

func (x *Buff) GetBuffType() uint32 {
	if x != nil {
		return x.BuffType
	}
	return 0
}

func (x *Buff) GetBuffLevel() int32 {
	if x != nil {
		return x.BuffLevel
	}
	return 0
}

func (x *Buff) GetBuffMaxTime() uint32 {
	if x != nil {
		return x.BuffMaxTime
	}
	return 0
}

func (x *Buff) GetBuffLeftTime() uint32 {
	if x != nil {
		return x.BuffLeftTime
	}
	return 0
}

func (x *Buff) GetMsgParams() string {
	if x != nil {
		return x.MsgParams
	}
	return ""
}

type PenaltyInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PenaltyType      uint32                 `protobuf:"varint,1,opt,name=penalty_type,json=penaltyType,proto3" json:"penalty_type,omitempty"`
	PenaltyEffectSec uint32                 `protobuf:"varint,2,opt,name=penalty_effect_sec,json=penaltyEffectSec,proto3" json:"penalty_effect_sec,omitempty"`
	TotalPenaltyNum  uint32                 `protobuf:"varint,3,opt,name=total_penalty_num,json=totalPenaltyNum,proto3" json:"total_penalty_num,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PenaltyInfo) Reset() {
	*x = PenaltyInfo{}
	mi := &file_pkg_rmcp_rmcp_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PenaltyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PenaltyInfo) ProtoMessage() {}

func (x *PenaltyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rmcp_rmcp_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PenaltyInfo.ProtoReflect.Descriptor instead.
func (*PenaltyInfo) Descriptor() ([]byte, []int) {
	return file_pkg_rmcp_rmcp_proto_rawDescGZIP(), []int{13}
}

func (x *PenaltyInfo) GetPenaltyType() uint32 {
	if x != nil {
		return x.PenaltyType
	}
	return 0
}

func (x *PenaltyInfo) GetPenaltyEffectSec() uint32 {
	if x != nil {
		return x.PenaltyEffectSec
	}
	return 0
}

func (x *PenaltyInfo) GetTotalPenaltyNum() uint32 {
	if x != nil {
		return x.TotalPenaltyNum
	}
	return 0
}

type RobotPathPlanInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Intention     uint32                 `protobuf:"varint,1,opt,name=intention,proto3" json:"intention,omitempty"`
	StartPosX     uint32                 `protobuf:"varint,2,opt,name=start_pos_x,json=startPosX,proto3" json:"start_pos_x,omitempty"`
	StartPosY     uint32                 `protobuf:"varint,3,opt,name=start_pos_y,json=startPosY,proto3" json:"start_pos_y,omitempty"`
	OffsetX       []int32                `protobuf:"varint,4,rep,packed,name=offset_x,json=offsetX,proto3" json:"offset_x,omitempty"`
	OffsetY       []int32                `protobuf:"varint,5,rep,packed,name=offset_y,json=offsetY,proto3" json:"offset_y,omitempty"`
	SenderId      uint32                 `protobuf:"varint,6,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RobotPathPlanInfo) Reset() {
	*x = RobotPathPlanInfo{}
	mi := &file_pkg_rmcp_rmcp_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RobotPathPlanInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RobotPathPlanInfo) ProtoMessage() {}

func (x *RobotPathPlanInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rmcp_rmcp_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RobotPathPlanInfo.ProtoReflect.Descriptor instead.
func (*RobotPathPlanInfo) Descriptor() ([]byte, []int) {
	return file_pkg_rmcp_rmcp_proto_rawDescGZIP(), []int{14}
}

func (x *RobotPathPlanInfo) GetIntention() uint32 {
	if x != nil {
		return x.Intention
	}
	return 0
}

func (x *RobotPathPlanInfo) GetStartPosX() uint32 {
	if x != nil {
		return x.StartPosX
	}
	return 0
}

func (x *RobotPathPlanInfo) GetStartPosY() uint32 {
	if x != nil {
		return x.StartPosY
	}
	return 0
}

func (x *RobotPathPlanInfo) GetOffsetX() []int32 {
	if x != nil {
		return x.OffsetX
	}
	return nil
}

func (x *RobotPathPlanInfo) GetOffsetY() []int32 {
	if x != nil {
		return x.OffsetY
	}
	return nil
}

func (x *RobotPathPlanInfo) GetSenderId() uint32 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

type MapClickInfoNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsSendAll     uint32                 `protobuf:"varint,1,opt,name=is_send_all,json=isSendAll,proto3" json:"is_send_all,omitempty"`
	RobotId       []byte                 `protobuf:"bytes,2,opt,name=robot_id,json=robotId,proto3" json:"robot_id,omitempty"`
	Mode          uint32                 `protobuf:"varint,3,opt,name=mode,proto3" json:"mode,omitempty"`
	EnemyId       uint32                 `protobuf:"varint,4,opt,name=enemy_id,json=enemyId,proto3" json:"enemy_id,omitempty"`
	Ascii         uint32                 `protobuf:"varint,5,opt,name=ascii,proto3" json:"ascii,omitempty"`
	Type          uint32                 `protobuf:"varint,6,opt,name=type,proto3" json:"type,omitempty"`
	ScreenX       uint32                 `protobuf:"varint,7,opt,name=screen_x,json=screenX,proto3" json:"screen_x,omitempty"`
	ScreenY       uint32                 `protobuf:"varint,8,opt,name=screen_y,json=screenY,proto3" json:"screen_y,omitempty"`
	MapX          float32                `protobuf:"fixed32,9,opt,name=map_x,json=mapX,proto3" json:"map_x,omitempty"`
	MapY          float32                `protobuf:"fixed32,10,opt,name=map_y,json=mapY,proto3" json:"map_y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapClickInfoNotify) Reset() {
	*x = MapClickInfoNotify{}
	mi := &file_pkg_rmcp_rmcp_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapClickInfoNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapClickInfoNotify) ProtoMessage() {}

func (x *MapClickInfoNotify) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rmcp_rmcp_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapClickInfoNotify.ProtoReflect.Descriptor instead.
func (*MapClickInfoNotify) Descriptor() ([]byte, []int) {
	return file_pkg_rmcp_rmcp_proto_rawDescGZIP(), []int{15}
}

func (x *MapClickInfoNotify) GetIsSendAll() uint32 {
	if x != nil {
		return x.IsSendAll
	}
	return 0
}

func (x *MapClickInfoNotify) GetRobotId() []byte {
	if x != nil {
		return x.RobotId
	}
	return nil
}

func (x *MapClickInfoNotify) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *MapClickInfoNotify) GetEnemyId() uint32 {
	if x != nil {
		return x.EnemyId
	}
	return 0
}

func (x *MapClickInfoNotify) GetAscii() uint32 {
	if x != nil {
		return x.Ascii
	}
	return 0
}

func (x *MapClickInfoNotify) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *MapClickInfoNotify) GetScreenX() uint32 {
	if x != nil {
		return x.ScreenX
	}
	return 0
}

func (x *MapClickInfoNotify) GetScreenY() uint32 {
	if x != nil {
		return x.ScreenY
	}
	return 0
}

func (x *MapClickInfoNotify) GetMapX() float32 {
	if x != nil {
		return x.MapX
	}
	return 0
}

func (x *MapClickInfoNotify) GetMapY() float32 {
	if x != nil {
		return x.MapY
	}
	return 0
}

type RaderInfoToClient struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetRobotId uint32                 `protobuf:"varint,1,opt,name=target_robot_id,json=targetRobotId,proto3" json:"target_robot_id,omitempty"`
	TargetPosX    float32                `protobuf:"fixed32,2,opt,name=target_pos_x,json=targetPosX,proto3" json:"target_pos_x,omitempty"`
	TargetPosY    float32                `protobuf:"fixed32,3,opt,name=target_pos_y,json=targetPosY,proto3" json:"target_pos_y,omitempty"`
	TorwardAngle  float32                `protobuf:"fixed32,4,opt,name=torward_angle,json=torwardAngle,proto3" json:"torward_angle,omitempty"`
	IsHighLight   uint32                 `protobuf:"varint,5,opt,name=is_high_light,json=isHighLight,proto3" json:"is_high_light,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaderInfoToClient) Reset() {
	*x = RaderInfoToClient{}
	mi := &file_pkg_rmcp_rmcp_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaderInfoToClient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaderInfoToClient) ProtoMessage() {}

func (x *RaderInfoToClient) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rmcp_rmcp_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaderInfoToClient.ProtoReflect.Descriptor instead.
func (*RaderInfoToClient) Descriptor() ([]byte, []int) {
	return file_pkg_rmcp_rmcp_proto_rawDescGZIP(), []int{16}
}

func (x *RaderInfoToClient) GetTargetRobotId() uint32 {
	if x != nil {
		return x.TargetRobotId
	}
	return 0
}

func (x *RaderInfoToClient) GetTargetPosX() float32 {
	if x != nil {
		return x.TargetPosX
	}
	return 0
}

func (x *RaderInfoToClient) GetTargetPosY() float32 {
	if x != nil {
		return x.TargetPosY
	}
	return 0
}

func (x *RaderInfoToClient) GetTorwardAngle() float32 {
	if x != nil {
		return x.TorwardAngle
	}
	return 0
}

func (x *RaderInfoToClient) GetIsHighLight() uint32 {
	if x != nil {
		return x.IsHighLight
	}
	return 0
}

type CustomByteBlock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomByteBlock) Reset() {
	*x = CustomByteBlock{}
	mi := &file_pkg_rmcp_rmcp_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomByteBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomByteBlock) ProtoMessage() {}

func (x *CustomByteBlock) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rmcp_rmcp_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomByteBlock.ProtoReflect.Descriptor instead.
func (*CustomByteBlock) Descriptor() ([]byte, []int) {
	return file_pkg_rmcp_rmcp_proto_rawDescGZIP(), []int{17}
}

func (x *CustomByteBlock) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type AssemblyCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operation     uint32                 `protobuf:"varint,1,opt,name=operation,proto3" json:"operation,omitempty"`
	Difficulty    uint32                 `protobuf:"varint,2,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssemblyCommand) Reset() {
	*x = AssemblyCommand{}
	mi := &file_pkg_rmcp_rmcp_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssemblyCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssemblyCommand) ProtoMessage() {}

func (x *AssemblyCommand) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rmcp_rmcp_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssemblyCommand.ProtoReflect.Descriptor instead.
func (*AssemblyCommand) Descriptor() ([]byte, []int) {
	return file_pkg_rmcp_rmcp_proto_rawDescGZIP(), []int{18}
}

func (x *AssemblyCommand) GetOperation() uint32 {
	if x != nil {
		return x.Operation
	}
	return 0
}

func (x *AssemblyCommand) GetDifficulty() uint32 {
	if x != nil {
		return x.Difficulty
	}
	return 0
}

type TechCoreMotionStateSync struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	MaximumDifficultyLevel uint32                 `protobuf:"varint,1,opt,name=maximum_difficulty_level,json=maximumDifficultyLevel,proto3" json:"maximum_difficulty_level,omitempty"`
	Status                 uint32                 `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *TechCoreMotionStateSync) Reset() {
	*x = TechCoreMotionStateSync{}
	mi := &file_pkg_rmcp_rmcp_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TechCoreMotionStateSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TechCoreMotionStateSync) ProtoMessage() {}

func (x *TechCoreMotionStateSync) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rmcp_rmcp_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TechCoreMotionStateSync.ProtoReflect.Descriptor instead.
func (*TechCoreMotionStateSync) Descriptor() ([]byte, []int) {
	return file_pkg_rmcp_rmcp_proto_rawDescGZIP(), []int{19}
}

func (x *TechCoreMotionStateSync) GetMaximumDifficultyLevel() uint32 {
	if x != nil {
		return x.MaximumDifficultyLevel
	}
	return 0
}

func (x *TechCoreMotionStateSync) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type RobotPerformanceSelectionCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shooter       uint32                 `protobuf:"varint,1,opt,name=shooter,proto3" json:"shooter,omitempty"`
	Chassis       uint32                 `protobuf:"varint,2,opt,name=chassis,proto3" json:"chassis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RobotPerformanceSelectionCommand) Reset() {
	*x = RobotPerformanceSelectionCommand{}
	mi := &file_pkg_rmcp_rmcp_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RobotPerformanceSelectionCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RobotPerformanceSelectionCommand) ProtoMessage() {}

func (x *RobotPerformanceSelectionCommand) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rmcp_rmcp_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RobotPerformanceSelectionCommand.ProtoReflect.Descriptor instead.
func (*RobotPerformanceSelectionCommand) Descriptor() ([]byte, []int) {
	return file_pkg_rmcp_rmcp_proto_rawDescGZIP(), []int{20}
}

func (x *RobotPerformanceSelectionCommand) GetShooter() uint32 {
	if x != nil {
		return x.Shooter
	}
	return 0
}

func (x *RobotPerformanceSelectionCommand) GetChassis() uint32 {
	if x != nil {
		return x.Chassis
	}
	return 0
}

type RobotPerformanceSelectionSync struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shooter       uint32                 `protobuf:"varint,1,opt,name=shooter,proto3" json:"shooter,omitempty"`
	Chassis       uint32                 `protobuf:"varint,2,opt,name=chassis,proto3" json:"chassis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RobotPerformanceSelectionSync) Reset() {
	*x = RobotPerformanceSelectionSync{}
	mi := &file_pkg_rmcp_rmcp_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RobotPerformanceSelectionSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RobotPerformanceSelectionSync) ProtoMessage() {}

func (x *RobotPerformanceSelectionSync) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rmcp_rmcp_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RobotPerformanceSelectionSync.ProtoReflect.Descriptor instead.
func (*RobotPerformanceSelectionSync) Descriptor() ([]byte, []int) {
	return file_pkg_rmcp_rmcp_proto_rawDescGZIP(), []int{21}
}

func (x *RobotPerformanceSelectionSync) GetShooter() uint32 {
	if x != nil {
		return x.Shooter
	}
	return 0
}

func (x *RobotPerformanceSelectionSync) GetChassis() uint32 {
	if x != nil {
		return x.Chassis
	}
	return 0
}

type HeroDeployModeEventCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          uint32                 `protobuf:"varint,1,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeroDeployModeEventCommand) Reset() {
	*x = HeroDeployModeEventCommand{}
	mi := &file_pkg_rmcp_rmcp_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeroDeployModeEventCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeroDeployModeEventCommand) ProtoMessage() {}

func (x *HeroDeployModeEventCommand) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rmcp_rmcp_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeroDeployModeEventCommand.ProtoReflect.Descriptor instead.
func (*HeroDeployModeEventCommand) Descriptor() ([]byte, []int) {
	return file_pkg_rmcp_rmcp_proto_rawDescGZIP(), []int{22}
}

func (x *HeroDeployModeEventCommand) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

type DeployModeStatusSync struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        uint32                 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployModeStatusSync) Reset() {
	*x = DeployModeStatusSync{}
	mi := &file_pkg_rmcp_rmcp_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployModeStatusSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployModeStatusSync) ProtoMessage() {}

func (x *DeployModeStatusSync) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rmcp_rmcp_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployModeStatusSync.ProtoReflect.Descriptor instead.
func (*DeployModeStatusSync) Descriptor() ([]byte, []int) {
	return file_pkg_rmcp_rmcp_proto_rawDescGZIP(), []int{23}
}

func (x *DeployModeStatusSync) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type RuneActivateCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Activate      uint32                 `protobuf:"varint,1,opt,name=activate,proto3" json:"activate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuneActivateCommand) Reset() {
	*x = RuneActivateCommand{}
	mi := &file_pkg_rmcp_rmcp_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuneActivateCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuneActivateCommand) ProtoMessage() {}

func (x *RuneActivateCommand) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rmcp_rmcp_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuneActivateCommand.ProtoReflect.Descriptor instead.
func (*RuneActivateCommand) Descriptor() ([]byte, []int) {
	return file_pkg_rmcp_rmcp_proto_rawDescGZIP(), []int{24}
}

func (x *RuneActivateCommand) GetActivate() uint32 {
	if x != nil {
		return x.Activate
	}
	return 0
}

type RuneStatusSync struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuneStatus    uint32                 `protobuf:"varint,1,opt,name=rune_status,json=runeStatus,proto3" json:"rune_status,omitempty"`
	ActivatedArms uint32                 `protobuf:"varint,2,opt,name=activated_arms,json=activatedArms,proto3" json:"activated_arms,omitempty"`
	AverageRings  uint32                 `protobuf:"varint,3,opt,name=average_rings,json=averageRings,proto3" json:"average_rings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuneStatusSync) Reset() {
	*x = RuneStatusSync{}
	mi := &file_pkg_rmcp_rmcp_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuneStatusSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuneStatusSync) ProtoMessage() {}

func (x *RuneStatusSync) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rmcp_rmcp_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuneStatusSync.ProtoReflect.Descriptor instead.
func (*RuneStatusSync) Descriptor() ([]byte, []int) {
	return file_pkg_rmcp_rmcp_proto_rawDescGZIP(), []int{25}
}

func (x *RuneStatusSync) GetRuneStatus() uint32 {
	if x != nil {
		return x.RuneStatus
	}
	return 0
}

func (x *RuneStatusSync) GetActivatedArms() uint32 {
	if x != nil {
		return x.ActivatedArms
	}
	return 0
}

func (x *RuneStatusSync) GetAverageRings() uint32 {
	if x != nil {
		return x.AverageRings
	}
	return 0
}

type SentinelStatusSync struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostureId     uint32                 `protobuf:"varint,1,opt,name=posture_id,json=postureId,proto3" json:"posture_id,omitempty"`
	IsWeakened    bool                   `protobuf:"varint,2,opt,name=is_weakened,json=isWeakened,proto3" json:"is_weakened,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SentinelStatusSync) Reset() {
	*x = SentinelStatusSync{}
	mi := &file_pkg_rmcp_rmcp_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SentinelStatusSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SentinelStatusSync) ProtoMessage() {}

func (x *SentinelStatusSync) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rmcp_rmcp_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SentinelStatusSync.ProtoReflect.Descriptor instead.
func (*SentinelStatusSync) Descriptor() ([]byte, []int) {
	return file_pkg_rmcp_rmcp_proto_rawDescGZIP(), []int{26}
}

func (x *SentinelStatusSync) GetPostureId() uint32 {
	if x != nil {
		return x.PostureId
	}
	return 0
}

func (x *SentinelStatusSync) GetIsWeakened() bool {
	if x != nil {
		return x.IsWeakened
	}
	return false
}

type DartCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetId      uint32                 `protobuf:"varint,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Open          bool                   `protobuf:"varint,2,opt,name=open,proto3" json:"open,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DartCommand) Reset() {
	*x = DartCommand{}
	mi := &file_pkg_rmcp_rmcp_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DartCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DartCommand) ProtoMessage() {}

func (x *DartCommand) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rmcp_rmcp_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DartCommand.ProtoReflect.Descriptor instead.
func (*DartCommand) Descriptor() ([]byte, []int) {
	return file_pkg_rmcp_rmcp_proto_rawDescGZIP(), []int{27}
}

func (x *DartCommand) GetTargetId() uint32 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *DartCommand) GetOpen() bool {
	if x != nil {
		return x.Open
	}
	return false
}

type DartSelectTargetStatusSync struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetId      uint32                 `protobuf:"varint,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Open          bool                   `protobuf:"varint,2,opt,name=open,proto3" json:"open,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DartSelectTargetStatusSync) Reset() {
	*x = DartSelectTargetStatusSync{}
	mi := &file_pkg_rmcp_rmcp_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DartSelectTargetStatusSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DartSelectTargetStatusSync) ProtoMessage() {}

func (x *DartSelectTargetStatusSync) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rmcp_rmcp_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DartSelectTargetStatusSync.ProtoReflect.Descriptor instead.
func (*DartSelectTargetStatusSync) Descriptor() ([]byte, []int) {
	return file_pkg_rmcp_rmcp_proto_rawDescGZIP(), []int{28}
}

func (x *DartSelectTargetStatusSync) GetTargetId() uint32 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *DartSelectTargetStatusSync) GetOpen() bool {
	if x != nil {
		return x.Open
	}
	return false
}

type GuardCtrlCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     uint32                 `protobuf:"varint,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GuardCtrlCommand) Reset() {
	*x = GuardCtrlCommand{}
	mi := &file_pkg_rmcp_rmcp_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuardCtrlCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuardCtrlCommand) ProtoMessage() {}

func (x *GuardCtrlCommand) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rmcp_rmcp_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuardCtrlCommand.ProtoReflect.Descriptor instead.
func (*GuardCtrlCommand) Descriptor() ([]byte, []int) {
	return file_pkg_rmcp_rmcp_proto_rawDescGZIP(), []int{29}
}

func (x *GuardCtrlCommand) GetCommandId() uint32 {
	if x != nil {
		return x.CommandId
	}
	return 0
}

type GuardCtrlResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     uint32                 `protobuf:"varint,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	ResultCode    uint32                 `protobuf:"varint,2,opt,name=result_code,json=resultCode,proto3" json:"result_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GuardCtrlResult) Reset() {
	*x = GuardCtrlResult{}
	mi := &file_pkg_rmcp_rmcp_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuardCtrlResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuardCtrlResult) ProtoMessage() {}

func (x *GuardCtrlResult) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rmcp_rmcp_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuardCtrlResult.ProtoReflect.Descriptor instead.
func (*GuardCtrlResult) Descriptor() ([]byte, []int) {
	return file_pkg_rmcp_rmcp_proto_rawDescGZIP(), []int{30}
}

func (x *GuardCtrlResult) GetCommandId() uint32 {
	if x != nil {
		return x.CommandId
	}
	return 0
}

func (x *GuardCtrlResult) GetResultCode() uint32 {
	if x != nil {
		return x.ResultCode
	}
	return 0
}

type AirSupportCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     uint32                 `protobuf:"varint,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AirSupportCommand) Reset() {
	*x = AirSupportCommand{}
	mi := &file_pkg_rmcp_rmcp_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AirSupportCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AirSupportCommand) ProtoMessage() {}

func (x *AirSupportCommand) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rmcp_rmcp_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AirSupportCommand.ProtoReflect.Descriptor instead.
func (*AirSupportCommand) Descriptor() ([]byte, []int) {
	return file_pkg_rmcp_rmcp_proto_rawDescGZIP(), []int{31}
}

func (x *AirSupportCommand) GetCommandId() uint32 {
	if x != nil {
		return x.CommandId
	}
	return 0
}

type AirSupportStatusSync struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AirsupportStatus uint32                 `protobuf:"varint,1,opt,name=airsupport_status,json=airsupportStatus,proto3" json:"airsupport_status,omitempty"`
	LeftTime         uint32                 `protobuf:"varint,2,opt,name=left_time,json=leftTime,proto3" json:"left_time,omitempty"`
	CostCoins        uint32                 `protobuf:"varint,3,opt,name=cost_coins,json=costCoins,proto3" json:"cost_coins,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AirSupportStatusSync) Reset() {
	*x = AirSupportStatusSync{}
	mi := &file_pkg_rmcp_rmcp_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AirSupportStatusSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AirSupportStatusSync) ProtoMessage() {}

func (x *AirSupportStatusSync) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rmcp_rmcp_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AirSupportStatusSync.ProtoReflect.Descriptor instead.
func (*AirSupportStatusSync) Descriptor() ([]byte, []int) {
	return file_pkg_rmcp_rmcp_proto_rawDescGZIP(), []int{32}
}

func (x *AirSupportStatusSync) GetAirsupportStatus() uint32 {
	if x != nil {
		return x.AirsupportStatus
	}
	return 0
}

func (x *AirSupportStatusSync) GetLeftTime() uint32 {
	if x != nil {
		return x.LeftTime
	}
	return 0
}

func (x *AirSupportStatusSync) GetCostCoins() uint32 {
	if x != nil {
		return x.CostCoins
	}
	return 0
}

var File_pkg_rmcp_rmcp_proto protoreflect.FileDescriptor

const file_pkg_rmcp_rmcp_proto_rawDesc = "" +
	"\n" +
	"\x13pkg/rmcp/rmcp.proto\"\x93\x02\n" +
	"\rRemoteControl\x12\x17\n" +
	"\amouse_x\x18\x01 \x01(\x05R\x06mouseX\x12\x17\n" +
	"\amouse_y\x18\x02 \x01(\x05R\x06mouseY\x12\x17\n" +
	"\amouse_z\x18\x03 \x01(\x05R\x06mouseZ\x12(\n" +
	"\x10left_button_down\x18\x04 \x01(\bR\x0eleftButtonDown\x12*\n" +
	"\x11right_button_down\x18\x05 \x01(\bR\x0frightButtonDown\x12%\n" +
	"\x0ekeyboard_value\x18\x06 \x01(\rR\rkeyboardValue\x12&\n" +
	"\x0fmid_button_down\x18\a \x01(\bR\rmidButtonDown\x12\x12\n" +
	"\x04data\x18\b \x01(\fR\x04data\"\xae\x02\n" +
	"\n" +
	"GameStatus\x12#\n" +
	"\rcurrent_round\x18\x01 \x01(\rR\fcurrentRound\x12!\n" +
	"\ftotal_rounds\x18\x02 \x01(\rR\vtotalRounds\x12\x1b\n" +
	"\tred_score\x18\x03 \x01(\rR\bredScore\x12\x1d\n" +
	"\n" +
	"blue_score\x18\x04 \x01(\rR\tblueScore\x12#\n" +
	"\rcurrent_stage\x18\x05 \x01(\rR\fcurrentStage\x12.\n" +
	"\x13stage_countdown_sec\x18\x06 \x01(\x05R\x11stageCountdownSec\x12*\n" +
	"\x11stage_elapsed_sec\x18\a \x01(\x05R\x0fstageElapsedSec\x12\x1b\n" +
	"\tis_paused\x18\b \x01(\bR\bisPaused\"\xe1\x02\n" +
	"\x10GlobalUnitStatus\x12\x1f\n" +
	"\vbase_health\x18\x01 \x01(\rR\n" +
	"baseHealth\x12\x1f\n" +
	"\vbase_status\x18\x02 \x01(\rR\n" +
	"baseStatus\x12\x1f\n" +
	"\vbase_shield\x18\x03 \x01(\rR\n" +
	"baseShield\x12%\n" +
	"\x0eoutpost_health\x18\x04 \x01(\rR\routpostHealth\x12%\n" +
	"\x0eoutpost_status\x18\x05 \x01(\rR\routpostStatus\x12!\n" +
	"\frobot_health\x18\x06 \x03(\rR\vrobotHealth\x12#\n" +
	"\rrobot_bullets\x18\a \x03(\x05R\frobotBullets\x12(\n" +
	"\x10total_damage_red\x18\b \x01(\rR\x0etotalDamageRed\x12*\n" +
	"\x11total_damage_blue\x18\t \x01(\rR\x0ftotalDamageBlue\"\xc4\x01\n" +
	"\x15GlobalLogisticsStatus\x12+\n" +
	"\x11remaining_economy\x18\x01 \x01(\rR\x10remainingEconomy\x124\n" +
	"\x16total_economy_obtained\x18\x02 \x01(\x04R\x14totalEconomyObtained\x12\x1d\n" +
	"\n" +
	"tech_level\x18\x03 \x01(\rR\ttechLevel\x12)\n" +
	"\x10encryption_level\x18\x04 \x01(\rR\x0fencryptionLevel\"i\n" +
	"\x16GlobalSpecialMechanism\x12!\n" +
	"\fmechanism_id\x18\x01 \x03(\rR\vmechanismId\x12,\n" +
	"\x12mechanism_time_sec\x18\x02 \x03(\x05R\x10mechanismTimeSec\"8\n" +
	"\x05Event\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\x05R\aeventId\x12\x14\n" +
	"\x05param\x18\x02 \x01(\tR\x05param\"\xd3\x03\n" +
	"\x0fRobotInjuryStat\x12!\n" +
	"\ftotal_damage\x18\x01 \x01(\rR\vtotalDamage\x12)\n" +
	"\x10collision_damage\x18\x02 \x01(\rR\x0fcollisionDamage\x126\n" +
	"\x17small_projectile_damage\x18\x03 \x01(\rR\x15smallProjectileDamage\x126\n" +
	"\x17large_projectile_damage\x18\x04 \x01(\rR\x15largeProjectileDamage\x12,\n" +
	"\x12dart_splash_damage\x18\x05 \x01(\rR\x10dartSplashDamage\x122\n" +
	"\x15module_offline_damage\x18\x06 \x01(\rR\x13moduleOfflineDamage\x12.\n" +
	"\x13wifi_offline_damage\x18\a \x01(\rR\x11wifiOfflineDamage\x12%\n" +
	"\x0epenalty_damage\x18\b \x01(\rR\rpenaltyDamage\x12,\n" +
	"\x12server_kill_damage\x18\t \x01(\rR\x10serverKillDamage\x12\x1b\n" +
	"\tkiller_id\x18\n" +
	" \x01(\rR\bkillerId\"\xbe\x02\n" +
	"\x12RobotRespawnStatus\x12,\n" +
	"\x12is_pending_respawn\x18\x01 \x01(\bR\x10isPendingRespawn\x124\n" +
	"\x16total_respawn_progress\x18\x02 \x01(\rR\x14totalRespawnProgress\x128\n" +
	"\x18current_respawn_progress\x18\x03 \x01(\rR\x16currentRespawnProgress\x12(\n" +
	"\x10can_free_respawn\x18\x04 \x01(\bR\x0ecanFreeRespawn\x121\n" +
	"\x15gold_cost_for_respawn\x18\x05 \x01(\rR\x12goldCostForRespawn\x12-\n" +
	"\x13can_pay_for_respawn\x18\x06 \x01(\bR\x10canPayForRespawn\"\xab\x04\n" +
	"\x11RobotStaticStatus\x12)\n" +
	"\x10connection_state\x18\x01 \x01(\rR\x0fconnectionState\x12\x1f\n" +
	"\vfield_state\x18\x02 \x01(\rR\n" +
	"fieldState\x12\x1f\n" +
	"\valive_state\x18\x03 \x01(\rR\n" +
	"aliveState\x12\x19\n" +
	"\brobot_id\x18\x04 \x01(\rR\arobotId\x12\x1d\n" +
	"\n" +
	"robot_type\x18\x05 \x01(\rR\trobotType\x12<\n" +
	"\x1aperformance_system_shooter\x18\x06 \x01(\rR\x18performanceSystemShooter\x12<\n" +
	"\x1aperformance_system_chassis\x18\a \x01(\rR\x18performanceSystemChassis\x12\x14\n" +
	"\x05level\x18\b \x01(\rR\x05level\x12\x1d\n" +
	"\n" +
	"max_health\x18\t \x01(\rR\tmaxHealth\x12\x19\n" +
	"\bmax_heat\x18\n" +
	" \x01(\rR\amaxHeat\x12,\n" +
	"\x12heat_cooldown_rate\x18\v \x01(\x02R\x10heatCooldownRate\x12\x1b\n" +
	"\tmax_power\x18\f \x01(\rR\bmaxPower\x12*\n" +
	"\x11max_buffer_energy\x18\r \x01(\rR\x0fmaxBufferEnergy\x12,\n" +
	"\x12max_chassis_energy\x18\x0e \x01(\rR\x10maxChassisEnergy\"\xf7\x04\n" +
	"\x12RobotDynamicStatus\x12%\n" +
	"\x0ecurrent_health\x18\x01 \x01(\rR\rcurrentHealth\x12!\n" +
	"\fcurrent_heat\x18\x02 \x01(\x02R\vcurrentHeat\x129\n" +
	"\x19last_projectile_fire_rate\x18\x03 \x01(\x02R\x16lastProjectileFireRate\x124\n" +
	"\x16current_chassis_energy\x18\x04 \x01(\rR\x14currentChassisEnergy\x122\n" +
	"\x15current_buffer_energy\x18\x05 \x01(\rR\x13currentBufferEnergy\x12-\n" +
	"\x12current_experience\x18\x06 \x01(\rR\x11currentExperience\x124\n" +
	"\x16experience_for_upgrade\x18\a \x01(\rR\x14experienceForUpgrade\x126\n" +
	"\x17total_projectiles_fired\x18\b \x01(\rR\x15totalProjectilesFired\x12%\n" +
	"\x0eremaining_ammo\x18\t \x01(\rR\rremainingAmmo\x12'\n" +
	"\x10is_out_of_combat\x18\n" +
	" \x01(\bR\risOutOfCombat\x125\n" +
	"\x17out_of_combat_countdown\x18\v \x01(\rR\x14outOfCombatCountdown\x12&\n" +
	"\x0fcan_remote_heal\x18\f \x01(\bR\rcanRemoteHeal\x12&\n" +
	"\x0fcan_remote_ammo\x18\r \x01(\bR\rcanRemoteAmmo\"\xd1\x02\n" +
	"\x11RobotModuleStatus\x12#\n" +
	"\rpower_manager\x18\x01 \x01(\rR\fpowerManager\x12\x12\n" +
	"\x04rfid\x18\x02 \x01(\rR\x04rfid\x12\x1f\n" +
	"\vlight_strip\x18\x03 \x01(\rR\n" +
	"lightStrip\x12#\n" +
	"\rsmall_shooter\x18\x04 \x01(\rR\fsmallShooter\x12\x1f\n" +
	"\vbig_shooter\x18\x05 \x01(\rR\n" +
	"bigShooter\x12\x10\n" +
	"\x03uwb\x18\x06 \x01(\rR\x03uwb\x12\x14\n" +
	"\x05armor\x18\a \x01(\rR\x05armor\x12-\n" +
	"\x12video_transmission\x18\b \x01(\rR\x11videoTransmission\x12\x1c\n" +
	"\tcapacitor\x18\t \x01(\rR\tcapacitor\x12'\n" +
	"\x0fmain_controller\x18\n" +
	" \x01(\rR\x0emainController\"K\n" +
	"\rRobotPosition\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\x12\f\n" +
	"\x01z\x18\x03 \x01(\x02R\x01z\x12\x10\n" +
	"\x03yaw\x18\x04 \x01(\x02R\x03yaw\"\xc6\x01\n" +
	"\x04Buff\x12\x19\n" +
	"\brobot_id\x18\x01 \x01(\rR\arobotId\x12\x1b\n" +
	"\tbuff_type\x18\x02 \x01(\rR\bbuffType\x12\x1d\n" +
	"\n" +
	"buff_level\x18\x03 \x01(\x05R\tbuffLevel\x12\"\n" +
	"\rbuff_max_time\x18\x04 \x01(\rR\vbuffMaxTime\x12$\n" +
	"\x0ebuff_left_time\x18\x05 \x01(\rR\fbuffLeftTime\x12\x1d\n" +
	"\n" +
	"msg_params\x18\x06 \x01(\tR\tmsgParams\"\x8a\x01\n" +
	"\vPenaltyInfo\x12!\n" +
	"\fpenalty_type\x18\x01 \x01(\rR\vpenaltyType\x12,\n" +
	"\x12penalty_effect_sec\x18\x02 \x01(\rR\x10penaltyEffectSec\x12*\n" +
	"\x11total_penalty_num\x18\x03 \x01(\rR\x0ftotalPenaltyNum\"\xcc\x01\n" +
	"\x11RobotPathPlanInfo\x12\x1c\n" +
	"\tintention\x18\x01 \x01(\rR\tintention\x12\x1e\n" +
	"\vstart_pos_x\x18\x02 \x01(\rR\tstartPosX\x12\x1e\n" +
	"\vstart_pos_y\x18\x03 \x01(\rR\tstartPosY\x12\x1d\n" +
	"\boffset_x\x18\x04 \x03(\x05B\x02\x10\x01R\aoffsetX\x12\x1d\n" +
	"\boffset_y\x18\x05 \x03(\x05B\x02\x10\x01R\aoffsetY\x12\x1b\n" +
	"\tsender_id\x18\x06 \x01(\rR\bsenderId\"\x88\x02\n" +
	"\x12MapClickInfoNotify\x12\x1e\n" +
	"\vis_send_all\x18\x01 \x01(\rR\tisSendAll\x12\x19\n" +
	"\brobot_id\x18\x02 \x01(\fR\arobotId\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\rR\x04mode\x12\x19\n" +
	"\benemy_id\x18\x04 \x01(\rR\aenemyId\x12\x14\n" +
	"\x05ascii\x18\x05 \x01(\rR\x05ascii\x12\x12\n" +
	"\x04type\x18\x06 \x01(\rR\x04type\x12\x19\n" +
	"\bscreen_x\x18\a \x01(\rR\ascreenX\x12\x19\n" +
	"\bscreen_y\x18\b \x01(\rR\ascreenY\x12\x13\n" +
	"\x05map_x\x18\t \x01(\x02R\x04mapX\x12\x13\n" +
	"\x05map_y\x18\n" +
	" \x01(\x02R\x04mapY\"\xc8\x01\n" +
	"\x11RaderInfoToClient\x12&\n" +
	"\x0ftarget_robot_id\x18\x01 \x01(\rR\rtargetRobotId\x12 \n" +
	"\ftarget_pos_x\x18\x02 \x01(\x02R\n" +
	"targetPosX\x12 \n" +
	"\ftarget_pos_y\x18\x03 \x01(\x02R\n" +
	"targetPosY\x12#\n" +
	"\rtorward_angle\x18\x04 \x01(\x02R\ftorwardAngle\x12\"\n" +
	"\ris_high_light\x18\x05 \x01(\rR\visHighLight\"%\n" +
	"\x0fCustomByteBlock\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"O\n" +
	"\x0fAssemblyCommand\x12\x1c\n" +
	"\toperation\x18\x01 \x01(\rR\toperation\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x02 \x01(\rR\n" +
	"difficulty\"k\n" +
	"\x17TechCoreMotionStateSync\x128\n" +
	"\x18maximum_difficulty_level\x18\x01 \x01(\rR\x16maximumDifficultyLevel\x12\x16\n" +
	"\x06status\x18\x02 \x01(\rR\x06status\"V\n" +
	" RobotPerformanceSelectionCommand\x12\x18\n" +
	"\ashooter\x18\x01 \x01(\rR\ashooter\x12\x18\n" +
	"\achassis\x18\x02 \x01(\rR\achassis\"S\n" +
	"\x1dRobotPerformanceSelectionSync\x12\x18\n" +
	"\ashooter\x18\x01 \x01(\rR\ashooter\x12\x18\n" +
	"\achassis\x18\x02 \x01(\rR\achassis\"0\n" +
	"\x1aHeroDeployModeEventCommand\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\rR\x04mode\".\n" +
	"\x14DeployModeStatusSync\x12\x16\n" +
	"\x06status\x18\x01 \x01(\rR\x06status\"1\n" +
	"\x13RuneActivateCommand\x12\x1a\n" +
	"\bactivate\x18\x01 \x01(\rR\bactivate\"}\n" +
	"\x0eRuneStatusSync\x12\x1f\n" +
	"\vrune_status\x18\x01 \x01(\rR\n" +
	"runeStatus\x12%\n" +
	"\x0eactivated_arms\x18\x02 \x01(\rR\ractivatedArms\x12#\n" +
	"\raverage_rings\x18\x03 \x01(\rR\faverageRings\"T\n" +
	"\x12SentinelStatusSync\x12\x1d\n" +
	"\n" +
	"posture_id\x18\x01 \x01(\rR\tpostureId\x12\x1f\n" +
	"\vis_weakened\x18\x02 \x01(\bR\n" +
	"isWeakened\">\n" +
	"\vDartCommand\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\rR\btargetId\x12\x12\n" +
	"\x04open\x18\x02 \x01(\bR\x04open\"M\n" +
	"\x1aDartSelectTargetStatusSync\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\rR\btargetId\x12\x12\n" +
	"\x04open\x18\x02 \x01(\bR\x04open\"1\n" +
	"\x10GuardCtrlCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\rR\tcommandId\"Q\n" +
	"\x0fGuardCtrlResult\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\rR\tcommandId\x12\x1f\n" +
	"\vresult_code\x18\x02 \x01(\rR\n" +
	"resultCode\"2\n" +
	"\x11AirSupportCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\rR\tcommandId\"\x7f\n" +
	"\x14AirSupportStatusSync\x12+\n" +
	"\x11airsupport_status\x18\x01 \x01(\rR\x10airsupportStatus\x12\x1b\n" +
	"\tleft_time\x18\x02 \x01(\rR\bleftTime\x12\x1d\n" +
	"\n" +
	"cost_coins\x18\x03 \x01(\rR\tcostCoinsB\x0fZ\rpkg/rmcp;rmcpb\x06proto3"

var (
	file_pkg_rmcp_rmcp_proto_rawDescOnce sync.Once
	file_pkg_rmcp_rmcp_proto_rawDescData []byte
)

func file_pkg_rmcp_rmcp_proto_rawDescGZIP() []byte {
	file_pkg_rmcp_rmcp_proto_rawDescOnce.Do(func() {
		file_pkg_rmcp_rmcp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_rmcp_rmcp_proto_rawDesc), len(file_pkg_rmcp_rmcp_proto_rawDesc)))
	})
	return file_pkg_rmcp_rmcp_proto_rawDescData
}

var file_pkg_rmcp_rmcp_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_pkg_rmcp_rmcp_proto_goTypes = []any{
	(*RemoteControl)(nil),                    // 0: RemoteControl
	(*GameStatus)(nil),                       // 1: GameStatus
	(*GlobalUnitStatus)(nil),                 // 2: GlobalUnitStatus
	(*GlobalLogisticsStatus)(nil),            // 3: GlobalLogisticsStatus
	(*GlobalSpecialMechanism)(nil),           // 4: GlobalSpecialMechanism
	(*Event)(nil),                            // 5: Event
	(*RobotInjuryStat)(nil),                  // 6: RobotInjuryStat
	(*RobotRespawnStatus)(nil),               // 7: RobotRespawnStatus
	(*RobotStaticStatus)(nil),                // 8: RobotStaticStatus
	(*RobotDynamicStatus)(nil),               // 9: RobotDynamicStatus
	(*RobotModuleStatus)(nil),                // 10: RobotModuleStatus
	(*RobotPosition)(nil),                    // 11: RobotPosition
	(*Buff)(nil),                             // 12: Buff
	(*PenaltyInfo)(nil),                      // 13: PenaltyInfo
	(*RobotPathPlanInfo)(nil),                // 14: RobotPathPlanInfo
	(*MapClickInfoNotify)(nil),               // 15: MapClickInfoNotify
	(*RaderInfoToClient)(nil),                // 16: RaderInfoToClient
	(*CustomByteBlock)(nil),                  // 17: CustomByteBlock
	(*AssemblyCommand)(nil),                  // 18: AssemblyCommand
	(*TechCoreMotionStateSync)(nil),          // 19: TechCoreMotionStateSync
	(*RobotPerformanceSelectionCommand)(nil), // 20: RobotPerformanceSelectionCommand
	(*RobotPerformanceSelectionSync)(nil),    // 21: RobotPerformanceSelectionSync
	(*HeroDeployModeEventCommand)(nil),       // 22: HeroDeployModeEventCommand
	(*DeployModeStatusSync)(nil),             // 23: DeployModeStatusSync
	(*RuneActivateCommand)(nil),              // 24: RuneActivateCommand
	(*RuneStatusSync)(nil),                   // 25: RuneStatusSync
	(*SentinelStatusSync)(nil),               // 26: SentinelStatusSync
	(*DartCommand)(nil),                      // 27: DartCommand
	(*DartSelectTargetStatusSync)(nil),       // 28: DartSelectTargetStatusSync
	(*GuardCtrlCommand)(nil),                 // 29: GuardCtrlCommand
	(*GuardCtrlResult)(nil),                  // 30: GuardCtrlResult
	(*AirSupportCommand)(nil),                // 31: AirSupportCommand
	(*AirSupportStatusSync)(nil),             // 32: AirSupportStatusSync
}
var file_pkg_rmcp_rmcp_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_rmcp_rmcp_proto_init() }
func file_pkg_rmcp_rmcp_proto_init() {
	if File_pkg_rmcp_rmcp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_rmcp_rmcp_proto_rawDesc), len(file_pkg_rmcp_rmcp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_rmcp_rmcp_proto_goTypes,
		DependencyIndexes: file_pkg_rmcp_rmcp_proto_depIdxs,
		MessageInfos:      file_pkg_rmcp_rmcp_proto_msgTypes,
	}.Build()
	File_pkg_rmcp_rmcp_proto = out.File
	file_pkg_rmcp_rmcp_proto_goTypes = nil
	file_pkg_rmcp_rmcp_proto_depIdxs = nil
}
